export const ADD_INGREDIENT: 'ADD_INGREDIENT' = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT: 'DELETE_INGREDIENT' = 'DELETE_INGREDIENT';
export const SET_BUNS: 'SET_BUNS' = 'SET_BUNS';
export const MOVE_INGREDIENT : 'MOVE_INGREDIENT'= 'MOVE_INGREDIENT';
export const RESET_INGREDIENTS: 'RESET_INGREDIENTS' = 'RESET_INGREDIENTS';

export const FORGOT_PASSWORD_FORM_SUBMIT: "FORGOT_PASSWORD_FORM_SUBMIT" = "FORGOT_PASSWORD_FORM_SUBMIT";
export const FORGOT_PASSWORD_FORM_SUCCESS: "FORGOT_PASSWORD_FORM_SUCCESS" = "FORGOT_PASSWORD_FORM_SUCCESS";
export const FORGOT_PASSWORD_FORM_ERROR: "FORGOT_PASSWORD_FORM_ERROR" = "FORGOT_PASSWORD_FORM_ERROR";

export const OPEN_INGREDIENT_MODAL: 'OPEN_INGREDIENT_MODAL' = 'OPEN_INGREDIENT_MODAL';
export const CLOSE_INGREDIENT_MODAL: 'CLOSE_INGREDIENT_MODAL' = 'CLOSE_INGREDIENT_MODAL';

export const SELECT_INGREDIENT: 'SELECT_INGREDIENT' = 'SELECT_INGREDIENT';
export const UNSELECT_INGREDIENT: 'UNSELECT_INGREDIENT' = 'UNSELECT_INGREDIENT';

export const INGREDIENTS_GET_REQUEST: 'INGREDIENTS_GET_REQUEST' = 'INGREDIENTS_GET_REQUEST';
export const INGREDIENTS_GET_SUCCESS: 'INGREDIENTS_GET_SUCCESS' = 'INGREDIENTS_GET_SUCCESS';
export const INGREDIENTS_GET_FAILED: 'INGREDIENTS_GET_FAILED' = 'INGREDIENTS_GET_FAILED';

export const INCREASE_INGREDIENT: 'INCREASE_INGREDIENT' = 'INCREASE_INGREDIENT';
export const DECREASE_INGREDIENT: 'DECREASE_INGREDIENT' = 'DECREASE_INGREDIENT';
export const RESET_COUNT_INGREDIENT: 'RESET_COUNT_INGREDIENT' = 'RESET_COUNT_INGREDIENT';

export const CHANGE_BUNS: 'CHANGE_BUNS' = 'CHANGE_BUNS';

export const TAB_SWITCH: 'TAB_SWITCH' = 'TAB_SWITCH';

export const LOGIN_FORM_SUBMIT: "LOGIN_FORM_SUBMIT" = "LOGIN_FORM_SUBMIT";
export const LOGIN_FORM_SUCCESS: "LOGIN_FORM_SUCCESS" = "LOGIN_FORM_SUCCESS";
export const LOGIN_FORM_ERROR: "LOGINT_FORM_ERROR" = "LOGINT_FORM_ERROR";

export const OPEN_ORDER_MODAL: 'OPEN_ORDER_MODAL' = 'OPEN_ORDER_MODAL';
export const CLOSE_ORDER_MODAL: 'CLOSE_ORDER_MODAL' = 'CLOSE_ORDER_MODAL';

export const ORDER_POST_REQUEST: 'ORDER_POST_REQUEST' = 'ORDER_POST_REQUEST';
export const ORDER_POST_SUCCESS: 'ORDER_POST_SUCCESS' = 'ORDER_POST_SUCCESS';
export const ORDER_POST_FAILED: 'ORDER_POST_FAILED' = 'ORDER_POST_FAILED';

export const EDIT_PROFILE_FORM_SUBMIT = "EDIT_PROFILE_FORM_SUBMIT";
export const EDIT_PROFILE_FORM_SUCCESS = "EDIT_PROFILE_FORM_SUCCESS";
export const EDIT_PROFILE_FORM_ERROR = "EDIT_PROFILE_FORM_ERROR";

export const GET_USER_REQUEST: "GET_USER_REQUEST" = "GET_USER_REQUEST";
export const GET_USER_SUCCESS: "GET_USER_SUCCESS" = "GET_USER_SUCCESS";
export const GET_USER_ERROR: "GET_USER_ERROR" = "GET_USER_ERROR";

export const REFRESH_TOKEN_REQUEST: "REFRESH_TOKEN_REQUEST" = "REFRESH_TOKEN_REQUEST";
export const REFRESH_TOKEN_SUCCESS: "REFRESH_TOKEN_SUCCESS" = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_ERROR: "REFRESH_TOKEN_ERROR" = "REFRESH_TOKEN_ERROR";

export const LOGOUT_REQUEST: "LOGOUT_REQUEST" = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS: "LOGOUT_SUCCESS" = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR: "LOGOUT_ERROR" = "LOGOUT_ERROR";

export const REGISTER_FORM_SUBMIT: "REGISTER_FORM_SUBMIT" = "REGISTER_FORM_SUBMIT";
export const REGISTER_FORM_SUCCESS: "REGISTER_FORM_SUCCESS" = "REGISTER_FORM_SUCCESS";
export const REGISTER_FORM_ERROR: "REGISTER_FORM_ERROR" = "REGISTER_FORM_ERROR";

export const RESET_PASSWORD_FORM_SUBMIT: "RESET_PASSWORD_FORM_SUBMIT" = "RESET_PASSWORD_FORM_SUBMIT";
export const RESET_PASSWORD_FORM_SUCCESS: "RESET_PASSWORD_FORM_SUCCESS" = "RESET_PASSWORD_FORM_SUCCESS";
export const RESET_PASSWORD_FORM_ERROR: "RESET_PASSWORD_FORM_ERROR"= "RESET_PASSWORD_FORM_ERROR";

export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_CLOSED_SUCCESS: 'WS_CONNECTION_CLOSED_SUCCESS' = 'WS_CONNECTION_CLOSED_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_ORDERS: 'WS_GET_ORDERS' = 'WS_GET_ORDERS';


export const WS_CONNECTION_USER_ORDERS_START: 'WS_CONNECTION_USER_ORDERS_START' = 'WS_CONNECTION_USER_ORDERS_START';
export const WS_CONNECTION_USER_ORDERS_SUCCESS: 'WS_CONNECTION_USER_ORDERS_SUCCESS' = 'WS_CONNECTION_USER_ORDERS_SUCCESS';
export const WS_CONNECTION_USER_ORDERS_CLOSED_SUCCESS: 'WS_CONNECTION_USER_ORDERS_CLOSED_SUCCESS' = 'WS_CONNECTION_USER_ORDERS_CLOSED_SUCCESS';
export const WS_CONNECTION_USER_ORDERS_ERROR: 'WS_CONNECTION_USER_ORDERS_ERROR' = 'WS_CONNECTION_USER_ORDERS_ERROR';
export const WS_CONNECTION_USER_ORDERS_CLOSED: 'WS_CONNECTION_USER_ORDERS_CLOSED' = 'WS_CONNECTION_USER_ORDERS_CLOSED';
export const WS_GET_USER_ORDERS: 'WS_GET_USER_ORDERS' = 'WS_GET_USER_ORDERS';

export const SET_CORRECT_ORDERS: 'SET_CORRECT_ORDERS' = 'SET_CORRECT_ORDERS';
export const SET_DONE_ORDERS: 'SET_DONE_ORDERS' = 'SET_DONE_ORDERS';
export const SELECT_ORDER: 'SELECT_ORDER' = 'SELECT_ORDER';
export const UNSELECT_ORDER: 'UNSELECT_ORDER' = 'UNSELECT_ORDER';